### ISSUE TITLE
why following code always return null,  I need number

### ISSUE THREAD

**Issue by cfx-gspos** [Conflux-Chain/ConfluxWeb#10]
callSol();
async function callSol() {
    const ConfluxWeb = require('conflux-web');
    const confluxWeb = new ConfluxWeb('http://testnet-jsonrpc.conflux-chain.org:12537');

    const contract = new confluxWeb.cfx.Contract(
        require('./build/birdgame.abi.json'),
        '0xcdf5441a834bd412116ed85c2735c229b057a3dc'
    );
    const account = confluxWeb.cfx.accounts.wallet.add(PRIVATE_KEY);
 
    console.log(await contract.methods.inc(1).call())
}

**Comment by resodo** [comment]
The repo is no longer actively maintained. Please use https://github.com/Conflux-Chain/js-conflux-sdk
