### ISSUE TITLE
Could not send CFX through node terminal

### ISSUE THREAD

**Issue by saarshah** [Conflux-Chain/ConfluxWeb#2]
I have followed [this](https://conflux-chain.github.io/conflux-doc/javascript-api/#confluxwebcfxsendsignedtransaction) link to generate tx and send to another account. My transaction receipt is '0x7685f4364b3d489c091d9df42b30493c3ed45114ef49a2b942a2e280c9a6b554'  which is generated by following code 
`var st = confluxWeb.cfx.sendSignedTransaction('0x' + tx.serialize().toString('hex'));` , and 

st is printed as follow; 

> Proxy [ PromiEvent {
>     resolve: [Function],
>     reject: [Function],
>     promise:
>      Promise {
>        '0x7685f4364b3d489c091d9df42b30493c3ed45114ef49a2b942a2e280c9a6b554',
>        domain: [Domain] },
>     eventEmitter: EventEmitter { _events: {}, _eventsCount: 0 } },
>   { get: [Function: proxyHandler] } ] 

when i search above tx the confluxscan.io shows following msg.

0x7685f4364b3d4...is packing, please wait.. How much time will be required to complete it and able to watch in my wallet. ?

**Comment by liuis** [comment]
@saarshah 
If you use a test network, you can quickly find tx in the blockchain browser.
